spring:
  profiles:
    active:
    - dev
---
server:
  port: 8100

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mokerson.build.pojo     # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: build-provider-department
  datasource:
  profiles: dev
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC   # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
  instance:
    instance-id: building-department-hystrix-01   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: build-property
  company.name: www.mokerson.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8100

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mokerson.build.pojo     # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: build-provider-department
  datasource:
  profiles: dev
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC   # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
  instance:
    instance-id: building-department-hystrix-01   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: build-property
  company.name: www.mokerson.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$